### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'Sequence' Error

### ISSUE THREAD

**Issue by dominus-imperium** [OliverSherouse/wbdata#67]
The wbdata python modual gives error of: "AttributeError: module 'collections' has no attribute 'Sequence'", when using python [3.10.] 
The  good place to see why this is the case is in this link:(https://stackoverflow.com/questions/69596494/unable-to-import-freegames-python-package-attributeerror-module-collections) Therefore i will not repeat it here.

It can be easily solved by replacing `import collections` with `import collections.abc as collections` in the api.py file. I am not sure if this works with other python version but for 3.10 any api request involving dates does not work without it.
